# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git clone https://github.com/rustyx/fuse-hello.git
        docker build fuse-hello -t hello
        docker run -i hello
        docker run -i --device /dev/fuse hello
        docker run -i --cap-add SYS_ADMIN --device /dev/fuse hello
    - name: Start Rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.DROPBOX }}
      with:
        args: mount mount "dropbox:/Jacky Kevin" dropbox
