# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Get Download Links
      run: |
        echo "::set-output name=action_ase::$(iwr https://api.github.com/repos/aseprite/aseprite/releases/latest | Select -ExpandProperty Content | jq -r '.assets[].browser_download_url')"
        echo "::set-output name=action_skia::$(iwr https://api.github.com/repos/aseprite/skia/releases/latest | Select -ExpandProperty Content | jq -r '.assets[].browser_download_url' | findstr Windows | findstr 64)"
        echo "::set-output name=action_tag::$(iwr https://api.github.com/repos/aseprite/aseprite/releases/latest | Select -ExpandProperty Content | jq -r '.tag_name')"
      id: links
    - name: Clone aseprite source
      run: |
        iwr -outf source.zip ${{ steps.links.outputs.action_ase }}
        7z x source.zip -y -oaseprite | findstr ing
    - name: Download compiled skia
      run: |
        iwr -outf skia.zip ${{ steps.links.outputs.action_skia }}
        7z x skia.zip -y -oskia | findstr ing
    - name: Find path
      id: path
      run: echo "::set-output name=working_path::$(pwd | findstr \)"
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@master
      with:
        arch: x64
        sdk: 10.0.18362.0
    - name: Compiling aseprite for Windows
      run: |
        choco install openssl.light -y
        cd aseprite
        mkdir build
        cd build
        cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia -DSKIA_DIR=${{ steps.path.outputs.working_path }}\skia -DSKIA_LIBRARY_DIR=${{ steps.path.outputs.working_path }}\skia\out\Release-x64 -DCMAKE_IGNORE_PATH="C:/ProgramData/chocolatey/bin/;C:/Strawberry/c/bin/" -G Ninja ..
        ninja aseprite
    - name: Archive bin
      run: |
        cd aseprite\build\bin
        7z -tzip a Aseprite-${{ steps.links.outputs.action_tag }}-win-x64.zip * -mx0 | findstr ing
        cd ..\..\..
        mv aseprite\build\bin\Aseprite-${{ steps.links.outputs.action_tag }}-win-x64.zip .
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        path: Aseprite-${{ steps.links.outputs.action_tag }}-win-x64.zip
