name: Qt-test
on:
  watch:
    types: [ started ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        iwr -outf libclang.7z https://download.qt.io/development_releases/prebuilt/libclang/libclang-release_80-based-windows-mingw_64.7z
        7z x libclang.7z
        rm libclang.7z
    
