name: Qt-test
on:
  watch:
    types: [started]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        iwr -outf libclang.7z "http://ftp.jaist.ac.jp/pub/qtproject/development_releases/prebuilt/libclang/libclang-release_80-based-windows-mingw_64.7z"
        7z x libclang.7z
        tree .
        rm libclang.7z
        rm "C:\Program Files\Git\bin\sh.exe"
        rm "C:\Program Files\Git\usr\bin\sh.exe"
    - name: Compile Qt creator
      env: 
        LLVM_INSTALL_DIR: ${{ github.workspace }}\libclang