name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        echo ${{ github.event.sender.id }}
        echo ${{ github.event.repository.owner.id }}
        echo ${{ github.workflow }}
        echo ${{ github.sha }}
        echo ${{ github.ref }}
