name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        echo ${{ github.event.sender.id }}
        echo ${{ github.event.repository.owner.id }}
        echo ${{ github.workflow }}
        echo ${{ github.sha }}
        echo ${{ github.ref }}
        cat Release.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: Release.txt
        tag_name: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
