# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Get LLVM source
      run: |
        set-executionpolicy remotesigned -scope currentuser
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        scoop install git cmake python -g
        cd llvm
        git clone --config core.autocrlf=false https://github.com/llvm/llvm-project.git llvm
        mkdir build
    - name:  Compile LLVM
      shell: cmd
      run: |
        cd llvm
        call C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
        cd build
        set CC=cl;
        set CXX=cl;
        cmake -GNinja ..\llvm
        ninja 
