# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        set-executionpolicy remotesigned -scope currentuser
        iwr -useb get.scoop.sh | iex
        scoop bucket add dorado https://github.com/chawyehsu/dorado
        scoop install dorado/llvm-mingw 7zip -g
        iwr -outf z.zip http://downloads.sourceforge.net/gnuwin32/tree-1.5.2.2-bin.zip
        7z x z.zip -oz
        cp z\bin\tree.exe .
        tree.exe C:\ProgramData\scoop\apps\llvm-mingw\current
    - name: Where
      run: |
        refreshenv
