# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: llvm/llvm-project
        token: ${{ secrets.work1 }}
        path: llvm
        fetch-depth: 0
    - name: Import GPG
      uses: crazy-max/ghaction-import-gpg@v2.1.1
      with:
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
        git_committer_name: Insouciant21
        git_committer_email: 48847364+Insouciant21@users.noreply.github.com
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    - name: Get LLVM source
      run: |
        #set-executionpolicy remotesigned -scope currentuser
        #iwr -useb get.scoop.sh | iex
        #scoop install ninja -g
        tree -f llvm
        mkdir build
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1
    - name:  Compile LLVM
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
        cd build
        set CC=cl;
        set CXX=cl;
        cmake -GNinja ..\llvm
        ninja 
